### PR TITLE
Adding JS support to HTML parser

### PR DESCRIPTION
**Pull request by zerismo**
#9

screenshot from 2016-10-16 23 23 20

### CODE REVIEW

**Comment by mbad0la** [comment]
@karanchahal please review this as you reported this.

**Comment by karanchahal** [comment]
Hey !
 I'm sorry for the late response.This looks very good,slight issue though. When I put a for loop inside JavaScript, the '<' sign appears to be highlighted.
Ideally it shouldn't ,please fix this issue 💃 

screenshot 26

 #**Thanks** !

**Comment by mbad0la** [comment]
@zerismo please follow-up on @karanchahal 's remarks.

**Comment by mbad0la** [comment]
@zerismo your PR will be closed in a day to make way for #12 
Please update if you want this merged.

**Pull request closed without merging**
